/* ==========================================================================
    PRODUCT DATABASE
   ========================================================================== */

const productDatabase = [
    // --- 15 ACADEMIC BOOKS ---
    { id: "academic1", type: "Book", category: "Academic", title: "Intermediate Accounting Volume 3", authorOrBrand: "Vhinson Jay Gaarcia", price: 2525.0, stock: 45, totalSold: 1250, releaseDate: "2025-01-15", imageFile: "images/academic/intermediate-accounting-volume-3.jpg", description: "Master advanced financial accounting principles with this comprehensive volume. It is absolutely perfect for students pursuing a CPA track." },
    { id: "academic2", type: "Book", category: "Academic", title: "Data Structures in C++", authorOrBrand: "D.S. Malik", price: 1755.0, stock: 14, totalSold: 1340, releaseDate: "2024-07-30", imageFile: "images/academic/data-structures-using-cpp.jpg", description: "Learn how to build efficient algorithms using C++. These are essential concepts for aspiring software engineers." },
    { id: "academic3", type: "Book", category: "Academic", title: "Discrete Math", authorOrBrand: "Kenneth Rosen", price: 2155.0, stock: 33, totalSold: 2120, releaseDate: "2024-02-14", imageFile: "images/academic/discrete-mathematics-and-its-applications.jpg", description: "Foundations essential for computer science are clearly explained. Tackle logic, proofs, and graph theory head-on." },
    { id: "academic4", type: "Book", category: "Academic", title: "Engineering Mechanics", authorOrBrand: "R.C. Hibbeler", price: 2599.0, stock: 7, totalSold: 1650, releaseDate: "2025-06-25", imageFile: "images/academic/engineering-mechanics.jpg", description: "Statics and dynamics fundamentals for engineering students. Develop your problem-solving skills with practical examples." },
    { id: "academic5", type: "Book", category: "Academic", title: "Foundation of Computer Science", authorOrBrand: "Behrouz A. Forouzan", price: 1985.0, stock: 30, totalSold: 1500, releaseDate: "2026-01-05", imageFile: "images/academic/foundation-of-computer-science.jpg", description: "Introduction to data, hardware, and core algorithms. A perfect starting point for tech-focused academics." },
    { id: "academic6", type: "Book", category: "Academic", title: "Human Anatomy and Physiology", authorOrBrand: "Elaine N. Marieb", price: 3405.0, stock: 11, totalSold: 3000, releaseDate: "2023-11-10", imageFile: "images/academic/human-anatomy-and-physiology.jpg", description: "Detailed exploration of human body systems. A crucial resource for medical and biology students." },
    { id: "academic7", type: "Book", category: "Academic", title: "Intro to Sociology", authorOrBrand: "Anthony Giddens", price: 1405.0, stock: 19, totalSold: 980, releaseDate: "2024-09-05", imageFile: "images/academic/introduction-to-sociology.jpg", description: "Understanding society, culture, and human interaction. Dive into the fundamental theories of social behavior." },
    { id: "academic8", type: "Book", category: "Academic", title: "Macroeconomics", authorOrBrand: "N. Gregory Mankiw", price: 1535.0, stock: 8, totalSold: 2100, releaseDate: "2025-02-10", imageFile: "images/academic/macroeconomics.jpg", description: "An accessible textbook providing a solid economic framework. Analyze global markets and national policies." },
    { id: "academic9", type: "Book", category: "Academic", title: "Mathematics in the Modern World", authorOrBrand: "Romeo Daligdig", price: 399.0, stock: 18, totalSold: 2500, releaseDate: "2023-10-22", imageFile: "images/academic/mathematics-in-the-modern-world.jpg", description: "Explore how mathematics shapes our modern reality. Gain a deeper appreciation for patterns and logic." },
    { id: "academic10", type: "Book", category: "Academic", title: "Microbiology", authorOrBrand: "Marjorie Cowan", price: 2199.0, stock: 25, totalSold: 670, releaseDate: "2025-03-11", imageFile: "images/academic/microbiology.jpg", description: "A clinical approach to understanding microbes and diseases. Perfect for nursing and health science programs." },
    { id: "academic11", type: "Book", category: "Academic", title: "Modern Biology", authorOrBrand: "Campbell & Reece", price: 2855.0, stock: 12, totalSold: 980, releaseDate: "2024-11-20", imageFile: "images/academic/modern-biology.jpg", description: "The premier undergraduate textbook for biological sciences. Covers everything from cellular biology to ecosystems." },
    { id: "academic12", type: "Book", category: "Academic", title: "Organic Chemistry", authorOrBrand: "K. Peter C. Vollhardt", price: 3105.0, stock: 5, totalSold: 840, releaseDate: "2025-12-01", imageFile: "images/academic/organic-chemistry.jpg", description: "Understand the structure and function of complex organic molecules. Master reaction mechanisms and synthesis." },
    { id: "academic13", type: "Book", category: "Academic", title: "Physics for Scientists and Engineers", authorOrBrand: "Serway & Jewett", price: 2899.0, stock: 40, totalSold: 1890, releaseDate: "2026-02-01", imageFile: "images/academic/physics-for-scientists-and-engineers.jpg", description: "Calculus-based physics covering mechanics, thermodynamics, and electromagnetism. Emphasizes conceptual understanding and real-world applications." },
    { id: "academic14", type: "Book", category: "Academic", title: "Psychology 101", authorOrBrand: "David G. Myers", price: 1255.0, stock: 55, totalSold: 3200, releaseDate: "2023-08-14", imageFile: "images/academic/psychology-101.jpg", description: "An engaging introduction to human behavior and mental processes. Discover what drives human thought and emotion." },
    { id: "academic15", type: "Book", category: "Academic", title: "World History", authorOrBrand: "William Duiker", price: 1805.0, stock: 22, totalSold: 1100, releaseDate: "2024-05-18", imageFile: "images/academic/world-history.jpg", description: "A comprehensive narrative of human civilization across the globe. Trace the development of cultures and nations." },

    // --- 10 MANGA ---
    { id: "manga1", type: "Book", category: "Fiction", title: "Attack on Titan Volume 3", authorOrBrand: "Hajime Isayama", price: 499.0, stock: 40, totalSold: 7800, releaseDate: "2018-09-01", imageFile: "images/manga/attack-on-titan-volume-3.jpg", description: "Humanity's fight against the Titans continues in this thrilling volume. Discover the secrets hidden outside the walls." },
    { id: "manga2", type: "Book", category: "Fiction", title: "Bleach Volume 2", authorOrBrand: "Tite Kubo", price: 455.0, stock: 15, totalSold: 4300, releaseDate: "2016-02-14", imageFile: "images/manga/bleach-volume-2.jpg", description: "Ichigo's Soul Reaper duties intensify as new enemies appear. He must master his powers to protect his friends." },
    { id: "manga3", type: "Book", category: "Fiction", title: "Death Note Volume 1", authorOrBrand: "Tsugumi Ohba", price: 525.0, stock: 12, totalSold: 9200, releaseDate: "2010-10-10", imageFile: "images/manga/death-note-volume-1.jpg", description: "Light finds a notebook of death and begins his dark crusade. Detective L races against time to stop him." },
    { id: "manga4", type: "Book", category: "Fiction", title: "Demon Slayer Volume 2", authorOrBrand: "Koyoharu Gotouge", price: 485.0, stock: 55, totalSold: 8500, releaseDate: "2020-11-20", imageFile: "images/manga/demon-slayer-volume-2.jpg", description: "Tanjiro faces new demonic threats to protect his sister. The battle tests his newfound strength and resolve." },
    { id: "manga5", type: "Book", category: "Fiction", title: "Fullmetal Alchemist Volume 5", authorOrBrand: "Hiromu Arakawa", price: 555.0, stock: 18, totalSold: 5800, releaseDate: "2012-04-18", imageFile: "images/manga/fullmetal-alchemist-volume-5.jpg", description: "The Elric brothers uncover dark secrets about the Philosopher's Stone. Their journey takes a very dangerous turn." },
    { id: "manga6", type: "Book", category: "Fiction", title: "Haikyuu Volume 4", authorOrBrand: "Haruichi Furudate", price: 455.0, stock: 42, totalSold: 7100, releaseDate: "2019-07-22", imageFile: "images/manga/haikyu-volume-4.jpg", description: "Karasuno gears up for the tournament with intense training. The team must overcome their limits to win." },
    { id: "manga7", type: "Book", category: "Fiction", title: "Jujutsu Kaisen Volume 6", authorOrBrand: "Gege Akutami", price: 485.0, stock: 60, totalSold: 8900, releaseDate: "2021-03-15", imageFile: "images/manga/jujutsu-kaisen-volume-6.jpg", description: "The Kyoto Goodwill Event begins with explosive cursed energy battles. Yuji faces off against formidable rivals." },
    { id: "manga8", type: "Book", category: "Fiction", title: "My Hero Academia Volume 1", authorOrBrand: "Kohei Horikoshi", price: 455.0, stock: 35, totalSold: 6700, releaseDate: "2017-06-05", imageFile: "images/manga/my-hero-academia-volume-1.jpg", description: "Izuku Midoriya's origin story begins right here. He inherits the ultimate power to become the greatest hero." },
    { id: "manga9", type: "Book", category: "Fiction", title: "Naruto Volume 3", authorOrBrand: "Masashi Kishimoto", price: 455.0, stock: 25, totalSold: 5200, releaseDate: "2015-05-10", imageFile: "images/manga/naruto-volume-3.jpg", description: "The Chunin Exams approach, bringing dangerous new challenges. Team 7 must prove their worth to survive." },
    { id: "manga10", type: "Book", category: "Fiction", title: "One Piece Volume 1", authorOrBrand: "Eiichiro Oda", price: 455.0, stock: 30, totalSold: 6100, releaseDate: "2014-08-20", imageFile: "images/manga/one-piece-volume-1.jpg", description: "Romance Dawn marks the beginning of Luffy's epic journey. Set sail with the Straw Hat Pirates today." },
    
    // --- 15 NON-FICTION BOOKS ---
    { id: "nonfiction1", type: "Book", category: "Non-Fiction", title: "Atomic Habits", authorOrBrand: "James Clear", price: 855.0, stock: 80, totalSold: 12000, releaseDate: "2018-10-16", imageFile: "images/non-fiction/atomic-habits.jpg", description: "Tiny changes lead to truly remarkable results. Learn how to build good habits and break the bad ones." },
    { id: "nonfiction2", type: "Book", category: "Non-Fiction", title: "Can't Hurt Me", authorOrBrand: "David Goggins", price: 955.0, stock: 75, totalSold: 13000, releaseDate: "2018-12-04", imageFile: "images/non-fiction/cant-hurt-me.jpg", description: "Master your mind and defy the odds with this powerful memoir. David Goggins shares his incredible journey of resilience." },
    { id: "nonfiction3", type: "Book", category: "Non-Fiction", title: "Dare to Lead", authorOrBrand: "Brené Brown", price: 885.0, stock: 40, totalSold: 6500, releaseDate: "2018-10-09", imageFile: "images/non-fiction/dare-to-lead.jpg", description: "Brave work and tough conversations are essential for great leadership. Discover how to lead with a whole heart." },
    { id: "nonfiction4", type: "Book", category: "Non-Fiction", title: "Deep Work", authorOrBrand: "Cal Newport", price: 795.0, stock: 55, totalSold: 7600, releaseDate: "2016-01-05", imageFile: "images/non-fiction/deep-work.jpg", description: "Learn the rules for focused success in a distracted world. Train your brain to achieve peak productivity." },
    { id: "nonfiction5", type: "Book", category: "Non-Fiction", title: "Essentialism", authorOrBrand: "Greg McKeown", price: 785.0, stock: 50, totalSold: 6800, releaseDate: "2014-04-15", imageFile: "images/non-fiction/essentialism.jpg", description: "The disciplined pursuit of less is the key to true focus. Regain control of your choices and your time." },
    { id: "nonfiction6", type: "Book", category: "Non-Fiction", title: "Good to Great", authorOrBrand: "Jim Collins", price: 899.0, stock: 28, totalSold: 8800, releaseDate: "2001-10-16", imageFile: "images/non-fiction/good-to-great.jpg", description: "Discover why some companies make the leap and others don't. Uncover the secrets of long-term business success." },
    { id: "nonfiction7", type: "Book", category: "Non-Fiction", title: "Outliers", authorOrBrand: "Malcolm Gladwell", price: 855.0, stock: 48, totalSold: 9400, releaseDate: "2008-11-18", imageFile: "images/non-fiction/outliers.jpg", description: "The story of success is much more complex than you think. Explore the hidden factors that create high achievers." },
    { id: "nonfiction8", type: "Book", category: "Non-Fiction", title: "Rich Dad Poor Dad", authorOrBrand: "Robert Kiyosaki", price: 755.0, stock: 65, totalSold: 15000, releaseDate: "1997-04-01", imageFile: "images/non-fiction/rich-dad-poor-dad.jpg", description: "Find out what the rich teach their kids about money. Transform your financial mindset today." },
    { id: "nonfiction9", type: "Book", category: "Non-Fiction", title: "Sapiens", authorOrBrand: "Yuval Noah Harari", price: 955.0, stock: 45, totalSold: 9800, releaseDate: "2015-02-10", imageFile: "images/non-fiction/sapiens.jpg", description: "A brief history of humankind from the Stone Age to the modern era. Understand how biology and history have defined us." },
    { id: "nonfiction10", type: "Book", category: "Non-Fiction", title: "Start with Why", authorOrBrand: "Simon Sinek", price: 755.0, stock: 62, totalSold: 9100, releaseDate: "2009-10-29", imageFile: "images/non-fiction/start-with-why.jpg", description: "Learn how great leaders inspire everyone to take action. Discover the fundamental purpose behind successful organizations." },
    { id: "nonfiction11", type: "Book", category: "Non-Fiction", title: "The 48 Laws of Power", authorOrBrand: "Robert Greene", price: 985.0, stock: 40, totalSold: 14500, releaseDate: "1998-09-01", imageFile: "images/non-fiction/the-48-laws-of-power.jpg", description: "Amoral, cunning, ruthless, and highly instructive. This book is the definitive guide to mastering power dynamics." },
    { id: "nonfiction12", type: "Book", category: "Non-Fiction", title: "The Psychology of Money", authorOrBrand: "Morgan Housel", price: 825.0, stock: 110, totalSold: 10200, releaseDate: "2020-09-08", imageFile: "images/non-fiction/the-psychology-of-money.jpg", description: "Read these timeless lessons on wealth, greed, and happiness. Learn how to make better sense of your financial decisions." },
    { id: "nonfiction13", type: "Book", category: "Non-Fiction", title: "Thinking, Fast and Slow", authorOrBrand: "Daniel Kahneman", price: 925.0, stock: 30, totalSold: 8400, releaseDate: "2011-10-25", imageFile: "images/non-fiction/thinking-fast-and-slow.jpg", description: "The two systems that drive the way we think are fascinating. Explore the biases of your intuition." },
    { id: "nonfiction14", type: "Book", category: "Non-Fiction", title: "Zero to One", authorOrBrand: "Peter Thiel", price: 825.0, stock: 35, totalSold: 7900, releaseDate: "2014-09-16", imageFile: "images/non-fiction/zero-to-one.jpg", description: "Notes on startups, or how to truly build the future. Peter Thiel shares his contrarian views on innovation." },
    { id: "nonfiction15", type: "Book", category: "Non-Fiction", title: "How to Win Friends and Influence People", authorOrBrand: "Dale Carnegie", price: 655.0, stock: 85, totalSold: 16000, releaseDate: "1936-10-01", imageFile: "images/non-fiction/how-to-win-friends-and-influence-people.jpg", description: "This classic manual on human relations has helped millions. Improve your social skills and build lasting connections." },

    // --- 5 CHILDREN BOOKS ---
    { id: "child1", type: "Book", category: "Children", title: "The Carrot Seed", authorOrBrand: "Ruth Krauss", price: 295.0, stock: 30, totalSold: 1200, releaseDate: "1945-05-01", imageFile: "images/children/the-carrot-seed.jpg", description: "A little boy plants a carrot seed and waits patiently for it to grow. His unwavering faith is eventually rewarded." },
    { id: "child2", type: "Book", category: "Children", title: "Shiloh", authorOrBrand: "Phyllis Reynolds Naylor", price: 355.0, stock: 25, totalSold: 3400, releaseDate: "1991-01-01", imageFile: "images/children/shiloh.jpg", description: "A young boy finds an abused beagle and risks everything to keep him safe. This touching story explores themes of morality and love." },
    { id: "child3", type: "Book", category: "Children", title: "Peppa's Magical Unicorn", authorOrBrand: "Scholastic", price: 199.0, stock: 50, totalSold: 5000, releaseDate: "2018-12-26", imageFile: "images/children/peppa-pig.jpg", description: "Peppa Pig goes on a magical adventure with her new unicorn friend. It's a delightful tale full of fun and imagination." },
    { id: "child4", type: "Book", category: "Children", title: "My Little Book of Fairy Stories", authorOrBrand: "Brown Watson", price: 245.0, stock: 40, totalSold: 2100, releaseDate: "2015-08-01", imageFile: "images/children/fairy-stories.jpg", description: "This charming collection brings classic fairy tales to life for a new generation. Perfect for bedtime reading with vivid illustrations." },
    { id: "child5", type: "Book", category: "Children", title: "A Wrinkle in Time", authorOrBrand: "Macmillan US", price: 425.0, stock: 60, totalSold: 8900, releaseDate: "1962-01-01", imageFile: "images/children/a-wrinkle-in-time.jpg", description: "Meg Murry travels through space and time to rescue her missing father. A thrilling sci-fi adventure that captivates young minds." },

    // --- 20 STATIONERY / SUPPLIES ---
    { id: "stationery1", type: "Stationery", category: "Office Supplies", title: "Casio Scientific Calculator", authorOrBrand: "Casio", price: 1455.0, stock: 85, totalSold: 3200, releaseDate: "2021-07-25", imageFile: "images/stationery/casio-scientific-calculator-fx-991ex.jpg", description: "ClassWiz series featuring an intuitive spreadsheet function." },
    { id: "stationery2", type: "Stationery", category: "Paper Supplies", title: "Cattleya Filler Notebook", authorOrBrand: "Cattleya", price: 35.0, stock: 500, totalSold: 8900, releaseDate: "2022-08-01", imageFile: "images/stationery/cattleya-filler-notebook.jpg", description: "Standard 80 leaves spiral notebook. Ideal for daily class notes." },
    { id: "stationery3", type: "Stationery", category: "Paper Supplies", title: "Clear Expanding Envelope", authorOrBrand: "Generic", price: 25.0, stock: 600, totalSold: 10800, releaseDate: "2023-01-05", imageFile: "images/stationery/clear-expanding-envelope-long.jpg", description: "Durable plastic envelope with a secure push lock." },
    { id: "stationery4", type: "Stationery", category: "Office Supplies", title: "Deli 2-Hole Puncher", authorOrBrand: "Deli", price: 155.0, stock: 90, totalSold: 1200, releaseDate: "2022-04-18", imageFile: "images/stationery/deli-2-hole-puncher.jpg", description: "Heavy-duty metal puncher for office documentation." },
    { id: "stationery5", type: "Stationery", category: "Office Supplies", title: "Elmer's Glue Stick 22g", authorOrBrand: "Elmer's", price: 65.0, stock: 220, totalSold: 2400, releaseDate: "2022-09-05", imageFile: "images/stationery/elmers-glue-stick.jpg", description: "Washable, no-run glue stick that applies smoothly." },
    { id: "stationery6", type: "Stationery", category: "Coloring Supplies", title: "Faber-Castell Color Pencils", authorOrBrand: "Faber-Castell", price: 285.0, stock: 110, totalSold: 1500, releaseDate: "2022-01-15", imageFile: "images/stationery/faber-castell-classic-color-pencils.jpg", description: "Vibrant, break-resistant color pencils. Perfect for school art projects." },
    { id: "stationery7", type: "Stationery", category: "Writing Supplies", title: "Faber-Castell Yellow Highlighter", authorOrBrand: "Faber-Castell", price: 45.0, stock: 200, totalSold: 9600, releaseDate: "2023-02-10", imageFile: "images/stationery/faber-castell-yellow-highlighter.jpg", description: "Super fluorescent highlighter for pinpoint text emphasis." },
    { id: "stationery8", type: "Stationery", category: "Office Supplies", title: "Joy Stapler with Remover", authorOrBrand: "Joy", price: 85.0, stock: 160, totalSold: 2100, releaseDate: "2023-08-11", imageFile: "images/stationery/joy-stapler-with-remover.jpg", description: "Standard #10 stapler with a built-in staple remover." },
    { id: "stationery9", type: "Stationery", category: "Office Supplies", title: "Maped Eraser (Pack of 2)", authorOrBrand: "Maped", price: 45.0, stock: 350, totalSold: 4100, releaseDate: "2022-11-20", imageFile: "images/stationery/maped-eraser.jpg", description: "Dust-free white eraser. Erases cleanly without smudging." },
    { id: "stationery10", type: "Stationery", category: "Office Supplies", title: "Metal Binder Clips", authorOrBrand: "Generic", price: 45.0, stock: 400, totalSold: 8900, releaseDate: "2021-08-30", imageFile: "images/stationery/metal-binder-clips.jpg", description: "Strong grip paper clips for thick document stacks." },
    { id: "stationery11", type: "Stationery", category: "Paper Supplies", title: "Moleskine Hardcover", authorOrBrand: "Moleskine", price: 1255.0, stock: 40, totalSold: 850, releaseDate: "2021-04-10", imageFile: "images/stationery/moleskine-classic-hardcover.jpg", description: "Premium dotted journal for creative note-taking." },
    { id: "stationery12", type: "Stationery", category: "Paper Supplies", title: "Muji Cahier Journal", authorOrBrand: "Muji", price: 655.0, stock: 60, totalSold: 1100, releaseDate: "2022-10-12", imageFile: "images/stationery/muji-cahier-journal.jpg", description: "Minimalist grid notebooks with smooth paper. Perfect for bullet journaling." },
    { id: "stationery13", type: "Stationery", category: "Writing Supplies", title: "Panda Ballpen Black", authorOrBrand: "Panda", price: 125.0, stock: 300, totalSold: 14200, releaseDate: "2023-01-01", imageFile: "images/stationery/panda-ballpen-black.jpg", description: "Smooth writing ballpoint pens for everyday use." },
    { id: "stationery14", type: "Stationery", category: "Writing Supplies", title: "Pentel Energel 0.5mm Blue", authorOrBrand: "Pentel", price: 75.0, stock: 90, totalSold: 1800, releaseDate: "2023-06-20", imageFile: "images/stationery/pentel-engergel-blue.jpg", description: "Quick-drying liquid gel pen. Smear-resistant and incredibly smooth." },
    { id: "stationery15", type: "Stationery", category: "Writing Supplies", title: "Pilot G-Tec C4 Black", authorOrBrand: "Pilot", price: 65.0, stock: 150, totalSold: 3400, releaseDate: "2022-05-15", imageFile: "images/stationery/pilot-g-tec-pen.jpg", description: "Ultra-fine 0.4mm gel pen for precise detailing." },
    { id: "stationery16", type: "Stationery", category: "Office Supplies", title: "Post-it Notes 3x3", authorOrBrand: "3M", price: 75.0, stock: 280, totalSold: 11500, releaseDate: "2021-06-14", imageFile: "images/stationery/post-it-notes.jpg", description: "100 sheets of reliable sticky notes." },
    { id: "stationery17", type: "Stationery", category: "Coloring Supplies", title: "Prang Watercolors 8 Colors", authorOrBrand: "Prang", price: 195.0, stock: 75, totalSold: 900, releaseDate: "2023-05-10", imageFile: "images/stationery/prang-watercolors-8-colors.jpg", description: "Semi-moist watercolors with a fine brush included." },
    { id: "stationery18", type: "Stationery", category: "Office Supplies", title: "Scotch Magic Tape", authorOrBrand: "3M", price: 115.0, stock: 140, totalSold: 1800, releaseDate: "2021-03-22", imageFile: "images/stationery/scotch-magic-tape-with-dispenser.jpg", description: "Invisible matte finish tape that vanishes on paper." },
    { id: "stationery19", type: "Stationery", category: "Writing Supplies", title: "Sharpie Marker Black", authorOrBrand: "Sharpie", price: 55.0, stock: 120, totalSold: 2100, releaseDate: "2021-11-05", imageFile: "images/stationery/sharpie-permanent-marker-black.jpg", description: "Fine point permanent marker for bold, lasting marks." },
    { id: "stationery20", type: "Stationery", category: "Paper Supplies", title: "Veco Yellow Pad Paper", authorOrBrand: "Veco", price: 45.0, stock: 450, totalSold: 13800, releaseDate: "2023-03-01", imageFile: "images/stationery/veco-yellow-pad-paper.jpg", description: "Standard 90 leaves legal pad with clear rulings." }
];