/* ==========================================================================
    PRODUCT DATABASE
    Contains the mock database (60 Items) mapped to proper sub-categories.
   ========================================================================== */

const productDatabase = [
    // --- 10 MANGA (Mapped to Fiction & Children) ---
    { id: "manga1", type: "Book", category: "Fiction", title: "Attack on Titan Volume 3", authorOrBrand: "Hajime Isayama", price: 500.0, stock: 40, totalSold: 7800, releaseDate: "2018-09-01", imageFile: "images/manga/attack-on-titan-volume-3.jpg", description: "Humanity's fight against the Titans continues." },
    { id: "manga2", type: "Book", category: "Fiction", title: "Bleach Volume 2", authorOrBrand: "Tite Kubo", price: 450.0, stock: 15, totalSold: 4300, releaseDate: "2016-02-14", imageFile: "images/manga/bleach-volume-2.jpg", description: "Ichigo's Soul Reaper duties intensify." },
    { id: "manga3", type: "Book", category: "Fiction", title: "Death Note Volume 1", authorOrBrand: "Tsugumi Ohba", price: 520.0, stock: 12, totalSold: 9200, releaseDate: "2010-10-10", imageFile: "images/manga/death-note-volume-1.jpg", description: "Light finds a notebook of death." },
    { id: "manga4", type: "Book", category: "Children", title: "Demon Slayer Volume 2", authorOrBrand: "Koyoharu Gotouge", price: 480.0, stock: 55, totalSold: 8500, releaseDate: "2020-11-20", imageFile: "images/manga/demon-slayer-volume-2.jpg", description: "Tanjiro faces new demonic threats." },
    { id: "manga5", type: "Book", category: "Fiction", title: "Fullmetal Alchemist Volume 5", authorOrBrand: "Hiromu Arakawa", price: 550.0, stock: 18, totalSold: 5800, releaseDate: "2012-04-18", imageFile: "images/manga/fullmetal-alchemist-volume-5.jpg", description: "The Elric brothers uncover dark secrets." },
    { id: "manga6", type: "Book", category: "Children", title: "Haikyuu Volume 4", authorOrBrand: "Haruichi Furudate", price: 450.0, stock: 42, totalSold: 7100, releaseDate: "2019-07-22", imageFile: "images/manga/haikyu-volume-4.jpg", description: "Karasuno gears up for the tournament." },
    { id: "manga7", type: "Book", category: "Fiction", title: "Jujutsu Kaisen Volume 6", authorOrBrand: "Gege Akutami", price: 480.0, stock: 60, totalSold: 8900, releaseDate: "2021-03-15", imageFile: "images/manga/jujutsu-kaisen-volume-6.jpg", description: "The Kyoto Goodwill Event begins." },
    { id: "manga8", type: "Book", category: "Children", title: "My Hero Academia Volume 1", authorOrBrand: "Kohei Horikoshi", price: 450.0, stock: 35, totalSold: 6700, releaseDate: "2017-06-05", imageFile: "images/manga/my-hero-academia-volume-1.jpg", description: "Izuku Midoriya's origin story." },
    { id: "manga9", type: "Book", category: "Children", title: "Naruto Volume 3", authorOrBrand: "Masashi Kishimoto", price: 450.0, stock: 25, totalSold: 5200, releaseDate: "2015-05-10", imageFile: "images/manga/naruto-volume-3.jpg", description: "The Chunin Exams approach." },
    { id: "manga10", type: "Book", category: "Children", title: "One Piece Volume 1", authorOrBrand: "Eiichiro Oda", price: 450.0, stock: 30, totalSold: 6100, releaseDate: "2014-08-20", imageFile: "images/manga/one-piece-volume-1.jpg", description: "Romance Dawn. Set sail with Luffy." },

    // --- 15 NON-FICTION (Mapped to Non-Fiction) ---
    { id: "nonfiction1", type: "Book", category: "Non-Fiction", title: "Atomic Habits", authorOrBrand: "James Clear", price: 850.0, stock: 80, totalSold: 12000, releaseDate: "2018-10-16", imageFile: "images/non-fiction/atomic-habits.jpg", description: "Tiny changes, remarkable results." },
    { id: "nonfiction2", type: "Book", category: "Non-Fiction", title: "Can't Hurt Me", authorOrBrand: "David Goggins", price: 950.0, stock: 75, totalSold: 13000, releaseDate: "2018-12-04", imageFile: "images/non-fiction/cant-hurt-me.jpg", description: "Master your mind and defy the odds." },
    { id: "nonfiction3", type: "Book", category: "Non-Fiction", title: "Dare to Lead", authorOrBrand: "Brené Brown", price: 880.0, stock: 40, totalSold: 6500, releaseDate: "2018-10-09", imageFile: "images/non-fiction/dare-to-lead.jpg", description: "Brave work. Tough conversations. Whole hearts." },
    { id: "nonfiction4", type: "Book", category: "Non-Fiction", title: "Deep Work", authorOrBrand: "Cal Newport", price: 790.0, stock: 55, totalSold: 7600, releaseDate: "2016-01-05", imageFile: "images/non-fiction/deep-work.jpg", description: "Rules for focused success in a distracted world." },
    { id: "nonfiction5", type: "Book", category: "Non-Fiction", title: "Essentialism", authorOrBrand: "Greg McKeown", price: 780.0, stock: 50, totalSold: 6800, releaseDate: "2014-04-15", imageFile: "images/non-fiction/essentialism.jpg", description: "The disciplined pursuit of less." },
    { id: "nonfiction6", type: "Book", category: "Non-Fiction", title: "Good to Great", authorOrBrand: "Jim Collins", price: 900.0, stock: 28, totalSold: 8800, releaseDate: "2001-10-16", imageFile: "images/non-fiction/good-to-great.jpg", description: "Why some companies make the leap and others don'tabElement." },
    { id: "nonfiction7", type: "Book", category: "Non-Fiction", title: "Outliers", authorOrBrand: "Malcolm Gladwell", price: 850.0, stock: 48, totalSold: 9400, releaseDate: "2008-11-18", imageFile: "images/non-fiction/outliers.jpg", description: "The story of success." },
    { id: "nonfiction8", type: "Book", category: "Non-Fiction", title: "Rich Dad Poor Dad", authorOrBrand: "Robert Kiyosaki", price: 750.0, stock: 65, totalSold: 15000, releaseDate: "1997-04-01", imageFile: "images/non-fiction/rich-dad-poor-dad.jpg", description: "What the rich teach their kids about money." },
    { id: "nonfiction9", type: "Book", category: "Non-Fiction", title: "Sapiens", authorOrBrand: "Yuval Noah Harari", price: 950.0, stock: 45, totalSold: 9800, releaseDate: "2015-02-10", imageFile: "images/non-fiction/sapiens.jpg", description: "A brief history of humankind." },
    { id: "nonfiction10", type: "Book", category: "Non-Fiction", title: "Start with Why", authorOrBrand: "Simon Sinek", price: 750.0, stock: 62, totalSold: 9100, releaseDate: "2009-10-29", imageFile: "images/non-fiction/start-with-why.jpg", description: "How great leaders inspire everyone to take action." },
    { id: "nonfiction11", type: "Book", category: "Non-Fiction", title: "The 48 Laws of Power", authorOrBrand: "Robert Greene", price: 980.0, stock: 40, totalSold: 14500, releaseDate: "1998-09-01", imageFile: "images/non-fiction/the-48-laws-of-power.jpg", description: "Amoral, cunning, ruthless, and instructive." },
    { id: "nonfiction12", type: "Book", category: "Non-Fiction", title: "The Psychology of Money", authorOrBrand: "Morgan Housel", price: 820.0, stock: 110, totalSold: 10200, releaseDate: "2020-09-08", imageFile: "images/non-fiction/the-psychology-of-money.jpg", description: "Timeless lessons on wealth and greed." },
    { id: "nonfiction13", type: "Book", category: "Non-Fiction", title: "Thinking, Fast and Slow", authorOrBrand: "Daniel Kahneman", price: 920.0, stock: 30, totalSold: 8400, releaseDate: "2011-10-25", imageFile: "images/non-fiction/thinking-fast-and-slow.jpg", description: "The two systems that drive the way we think." },
    { id: "nonfiction14", type: "Book", category: "Non-Fiction", title: "Zero to One", authorOrBrand: "Peter Thiel", price: 820.0, stock: 35, totalSold: 7900, releaseDate: "2014-09-16", imageFile: "images/non-fiction/zero-to-one.jpg", description: "Notes on startups, or how to build the future." },
    { id: "nonfiction15", type: "Book", category: "Non-Fiction", title: "How to Win Friends and Influence People", authorOrBrand: "Dale Carnegie", price: 650.0, stock: 85, totalSold: 16000, releaseDate: "1936-10-01", imageFile: "images/non-fiction/how-to-win-friends-and-influence-people.jpg", description: "The classic manual on human relations." },

    // --- 15 ACADEMIC BOOKS (Mapped to Academic) ---
    { id: "academic1", type: "Book", category: "Academic", title: "Advanced Calculus", authorOrBrand: "James Stewart", price: 2520.0, stock: 45, totalSold: 1250, releaseDate: "2025-01-15", imageFile: "images/academic/advanced-calculus.jpg", description: "The industry standard, featuring clear explanations." },
    { id: "academic2", type: "Book", category: "Academic", title: "Data Structures in C++", authorOrBrand: "D.S. Malik", price: 1750.0, stock: 14, totalSold: 1340, releaseDate: "2024-07-30", imageFile: "images/academic/data-structures-using-cpp.jpg", description: "Learn how to build efficient algorithms." },
    { id: "academic3", type: "Book", category: "Academic", title: "Discrete Math", authorOrBrand: "Kenneth Rosen", price: 2150.0, stock: 33, totalSold: 2120, releaseDate: "2024-02-14", imageFile: "images/academic/discrete-mathematics-and-its-applications.jpg", description: "Foundations essential for computer science." },
    { id: "academic4", type: "Book", category: "Academic", title: "Engineering Mechanics", authorOrBrand: "R.C. Hibbeler", price: 2600.0, stock: 7, totalSold: 1650, releaseDate: "2025-06-25", imageFile: "images/academic/engineering-mechanics.jpg", description: "Statics and dynamics fundamentals." },
    { id: "academic5", type: "Book", category: "Academic", title: "Foundation of Computer Science", authorOrBrand: "Behrouz A. Forouzan", price: 1980.0, stock: 30, totalSold: 1500, releaseDate: "2026-01-05", imageFile: "images/academic/foundation-of-computer-science.jpg", description: "Introduction to data, hardware, and algorithms." },
    { id: "academic6", type: "Book", category: "Academic", title: "Human Anatomy and Physiology", authorOrBrand: "Elaine N. Marieb", price: 3400.0, stock: 11, totalSold: 3000, releaseDate: "2023-11-10", imageFile: "images/academic/human-anatomy-and-physiology.jpg", description: "Detailed exploration of human body systems." },
    { id: "academic7", type: "Book", category: "Academic", title: "Intro to Sociology", authorOrBrand: "Anthony Giddens", price: 1400.0, stock: 19, totalSold: 980, releaseDate: "2024-09-05", imageFile: "images/academic/introduction-to-sociology.jpg", description: "Understanding society and culture." },
    { id: "academic8", type: "Book", category: "Academic", title: "Macroeconomics", authorOrBrand: "N. Gregory Mankiw", price: 1530.0, stock: 8, totalSold: 2100, releaseDate: "2025-02-10", imageFile: "images/academic/macroeconomics.jpg", description: "Accessible textbook providing an economic framework." },
    { id: "academic9", type: "Book", category: "Academic", title: "Marketing Management", authorOrBrand: "Philip Kotler", price: 2100.0, stock: 18, totalSold: 2500, releaseDate: "2023-10-22", imageFile: "images/academic/marketing-management.jpg", description: "The gold standard for marketing students." },
    { id: "academic10", type: "Book", category: "Academic", title: "Microbiology", authorOrBrand: "Marjorie Cowan", price: 2200.0, stock: 25, totalSold: 670, releaseDate: "2025-03-11", imageFile: "images/academic/microbiology.jpg", description: "A clinical approach to understanding microbes." },
    { id: "academic11", type: "Book", category: "Academic", title: "Modern Biology", authorOrBrand: "Campbell & Reece", price: 2850.5, stock: 12, totalSold: 980, releaseDate: "2024-11-20", imageFile: "images/academic/modern-biology.jpg", description: "The premier undergraduate textbook." },
    { id: "academic12", type: "Book", category: "Academic", title: "Organic Chemistry", authorOrBrand: "K. Peter C. Vollhardt", price: 3100.0, stock: 5, totalSold: 840, releaseDate: "2025-12-01", imageFile: "images/academic/organic-chemistry.jpg", description: "Structure and function of organic molecules." },
    { id: "academic13", type: "Book", category: "Academic", title: "Physics for Scientists and Engineers", authorOrBrand: "Serway & Jewett", price: 2900.0, stock: 40, totalSold: 1890, releaseDate: "2026-02-01", imageFile: "images/academic/physics-for-scientists-and-engineers.jpg", description: "Physics for Scientists and Engineers is a widely used textbook series designed for introductory calculus-based physics courses, emphasizing conceptual understanding, problem-solving skills, and real-world applications. The book covers core topics in classical and modern physics, including mechanics, thermodynamics, electromagnetism, optics, and quantum physics, with editions tailored for different academic levels and pedagogical approaches." },
    { id: "academic14", type: "Book", category: "Academic", title: "Psychology 101", authorOrBrand: "David G. Myers", price: 1250.0, stock: 55, totalSold: 3200, releaseDate: "2023-08-14", imageFile: "images/academic/psychology-101.jpg", description: "An engaging introduction to human behavior." },
    { id: "academic15", type: "Book", category: "Academic", title: "World History", authorOrBrand: "William Duiker", price: 1800.0, stock: 22, totalSold: 1100, releaseDate: "2024-05-18", imageFile: "images/academic/world-history.jpg", description: "Narrative of human civilization." },

    // --- 20 STATIONERY / SUPPLIES ---
    { id: "stationery1", type: "Stationery", category: "Office Supplies", title: "Casio Scientific Calculator", authorOrBrand: "Casio", price: 1450.0, stock: 85, totalSold: 3200, releaseDate: "2021-07-25", imageFile: "images/stationery/casio-scientific-calculator-fx-991ex.jpg", description: "ClassWiz series with spreadsheet function." },
    { id: "stationery2", type: "Stationery", category: "Paper Supplies", title: "Cattleya Filler Notebook", authorOrBrand: "Cattleya", price: 35.0, stock: 500, totalSold: 8900, releaseDate: "2022-08-01", imageFile: "images/stationery/cattleya-filler-notebook.jpg", description: "Standard 80 leaves spiral notebook." },
    { id: "stationery3", type: "Stationery", category: "Paper Supplies", title: "Clear Expanding Envelope", authorOrBrand: "Generic", price: 25.0, stock: 600, totalSold: 10800, releaseDate: "2023-01-05", imageFile: "images/stationery/clear-expanding-envelope-long.jpg", description: "Plastic envelope with push lock." },
    { id: "stationery4", type: "Stationery", category: "Office Supplies", title: "Deli 2-Hole Puncher", authorOrBrand: "Deli", price: 150.0, stock: 90, totalSold: 1200, releaseDate: "2022-04-18", imageFile: "images/stationery/deli-2-hole-puncher.jpg", description: "Heavy duty metal puncher." },
    { id: "stationery5", type: "Stationery", category: "Office Supplies", title: "Elmer's Glue Stick 22g", authorOrBrand: "Elmer's", price: 65.0, stock: 220, totalSold: 2400, releaseDate: "2022-09-05", imageFile: "images/stationery/elmers-glue-stick.jpg", description: "Washable, no-run glue stick." },
    { id: "stationery6", type: "Stationery", category: "Coloring Supplies", title: "Faber-Castell Color Pencils", authorOrBrand: "Faber-Castell", price: 280.0, stock: 110, totalSold: 1500, releaseDate: "2022-01-15", imageFile: "images/stationery/faber-castell-classic-color-pencils.jpg", description: "Vibrant, break-resistant lead." },
    { id: "stationery7", type: "Stationery", category: "Writing Supplies", title: "Faber-Castell Yellow Highlighter", authorOrBrand: "Faber-Castell", price: 45.0, stock: 200, totalSold: 9600, releaseDate: "2023-02-10", imageFile: "images/stationery/faber-castell-yellow-highlighter.jpg", description: "Super fluorescent highlighter." },
    { id: "stationery8", type: "Stationery", category: "Office Supplies", title: "Joy Stapler with Remover", authorOrBrand: "Joy", price: 85.0, stock: 160, totalSold: 2100, releaseDate: "2023-08-11", imageFile: "images/stationery/joy-stapler-with-remover.jpg", description: "Standard #10 stapler." },
    { id: "stationery9", type: "Stationery", category: "Office Supplies", title: "Maped Eraser (Pack of 2)", authorOrBrand: "Maped", price: 40.0, stock: 350, totalSold: 4100, releaseDate: "2022-11-20", imageFile: "images/stationery/maped-eraser.jpg", description: "Dust-free white eraser." },
    { id: "stationery10", type: "Stationery", category: "Office Supplies", title: "Metal Binder Clips", authorOrBrand: "Generic", price: 45.0, stock: 400, totalSold: 8900, releaseDate: "2021-08-30", imageFile: "images/stationery/metal-binder-clips.jpg", description: "Strong grip paper clips." },
    { id: "stationery11", type: "Stationery", category: "Paper Supplies", title: "Moleskine Hardcover", authorOrBrand: "Moleskine", price: 1250.0, stock: 40, totalSold: 850, releaseDate: "2021-04-10", imageFile: "images/stationery/moleskine-classic-hardcover.jpg", description: "Premium dotted journal." },
    { id: "stationery12", type: "Stationery", category: "Paper Supplies", title: "Muji Cahier Journal", authorOrBrand: "Muji", price: 650.0, stock: 60, totalSold: 1100, releaseDate: "2022-10-12", imageFile: "images/stationery/muji-cahier-journal.jpg", description: "Minimalist grid notebooks." },
    { id: "stationery13", type: "Stationery", category: "Writing Supplies", title: "Panda Ballpen Black", authorOrBrand: "Panda", price: 120.0, stock: 300, totalSold: 14200, releaseDate: "2023-01-01", imageFile: "images/stationery/panda-ballpen-black.jpg", description: "Smooth writing ballpoint pens." },
    { id: "stationery14", type: "Stationery", category: "Writing Supplies", title: "Pentel Energel 0.5mm Blue", authorOrBrand: "Pentel", price: 75.0, stock: 90, totalSold: 1800, releaseDate: "2023-06-20", imageFile: "images/stationery/pentel-engergel-blue.jpg", description: "Quick-drying liquid gel pen." },
    { id: "stationery15", type: "Stationery", category: "Writing Supplies", title: "Pilot G-Tec C4 Black", authorOrBrand: "Pilot", price: 65.0, stock: 150, totalSold: 3400, releaseDate: "2022-05-15", imageFile: "images/stationery/pilot-g-tec-pen.jpg", description: "Ultra-fine 0.4mm gel pen." },
    { id: "stationery16", type: "Stationery", category: "Office Supplies", title: "Post-it Notes 3x3", authorOrBrand: "3M", price: 75.0, stock: 280, totalSold: 11500, releaseDate: "2021-06-14", imageFile: "images/stationery/post-it-notes.jpg", description: "100 sheets sticky notes." },
    { id: "stationery17", type: "Stationery", category: "Coloring Supplies", title: "Prang Watercolors 8 Colors", authorOrBrand: "Prang", price: 195.0, stock: 75, totalSold: 900, releaseDate: "2023-05-10", imageFile: "images/stationery/prang-watercolors-8-colors.jpg", description: "Semi-moist watercolors with brush." },
    { id: "stationery18", type: "Stationery", category: "Office Supplies", title: "Scotch Magic Tape", authorOrBrand: "3M", price: 110.0, stock: 140, totalSold: 1800, releaseDate: "2021-03-22", imageFile: "images/stationery/scotch-magic-tape-with-dispenser.jpg", description: "Invisible matte finish tape." },
    { id: "stationery19", type: "Stationery", category: "Writing Supplies", title: "Sharpie Marker Black", authorOrBrand: "Sharpie", price: 55.0, stock: 120, totalSold: 2100, releaseDate: "2021-11-05", imageFile: "images/stationery/sharpie-permanent-marker-black.jpg", description: "Fine point permanent marker." },
    { id: "stationery20", type: "Stationery", category: "Paper Supplies", title: "Veco Yellow Pad Paper", authorOrBrand: "Veco", price: 45.0, stock: 450, totalSold: 13800, releaseDate: "2023-03-01", imageFile: "images/stationery/veco-yellow-pad-paper.jpg", description: "Standard 90 leaves legal pad." }
];